#pragma once
#include "CoreMinimal.h"
#include "NiagaraCommon.h"

#include "NiagaraAnimNotifies/Public/AnimNotifyState_TimedNiagaraEffect.h"

#include "SAnimNotifyState_TimedNiagaraEffect.generated.h"

UCLASS(Blueprintable, meta = (DisplayName = "SG Timed Niagara Effect"))
class SOULSGAME_API USAnimNotifyState_TimedNiagaraEffect : public UAnimNotifyState_TimedNiagaraEffect
{
public:
	GENERATED_UCLASS_BODY()

	UFUNCTION(BlueprintCallable, Category = Niagara, meta = (Keywords = "niagara System", UnsafeDuringActorConstruction = "true"))
	static UNiagaraComponent* SpawnSystemAttached(UNiagaraSystem* SystemTemplate, USceneComponent* AttachToComponent, FName AttachPointName, FVector Location, FRotator Rotation, FVector Scale, EAttachLocation::Type LocationType, bool bAutoDestroy, bool bAutoActivate = true, ENCPoolMethod PoolingMethod = ENCPoolMethod::None, bool bPreCullCheck = true);

	// Offset from the socket / bone location
	UPROPERTY(EditAnywhere, Category = NiagaraSystem, meta = (ToolTip = "Scale of the spawned the Niagara effect"))
	FVector SpawnScale = FVector(1,1,1);

	UPROPERTY(EditAnywhere)
	bool bIsAutoGenerated = false;
	
protected:
	// Spawns the NiagaraSystemComponent. Called from Notify.
	virtual UFXSystemComponent* SpawnEffect(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation) const override;
};
